name: Test & Deploy
on:
  push:
    branches:
      - main

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/itsbalamurali/code-challenge:${{ github.sha }}
        build-args: GIT_SHA=${{ github.sha }}