name: Test, Build & Deploy
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Rust Cache
      uses: Swatinem/rust-cache@v1

    - name: Run Cargo Test
      run: cargo test
      env:
        GIT_SHA: ${{ github.sha }}

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/itsbalamurali/code-challenge:${{ github.sha }}
        build-args: GIT_SHA=${{ github.sha }}