name: Test & Deploy
on:
  push:
    branches:
      - main

jobs:
  setup-build-publish-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: ghcr.io/itsbalamurali/code-challenge:${{ github.sha }}
        build-args: GIT_SHA=${{ github.sha }}